// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmESOcxINXv7TB-8baBaKgf2k_dxNEtFI',
    appId: '1:459784963936:web:e7addc4aca0ca63cd30005',
    messagingSenderId: '459784963936',
    projectId: 'medicaments-f5daa',
    authDomain: 'medicaments-f5daa.firebaseapp.com',
    databaseURL: 'https://medicaments-f5daa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medicaments-f5daa.firebasestorage.app',
    measurementId: 'G-E9TTHVHBDG',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCym_DSoomi5UmXeKtOCc3jOJigIjWnoho',
    appId: '1:459784963936:ios:f6f87d65fa9fdf55d30005',
    messagingSenderId: '459784963936',
    projectId: 'medicaments-f5daa',
    databaseURL: 'https://medicaments-f5daa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medicaments-f5daa.firebasestorage.app',
    iosBundleId: 'com.example.medicaments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCym_DSoomi5UmXeKtOCc3jOJigIjWnoho',
    appId: '1:459784963936:ios:f6f87d65fa9fdf55d30005',
    messagingSenderId: '459784963936',
    projectId: 'medicaments-f5daa',
    databaseURL: 'https://medicaments-f5daa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medicaments-f5daa.firebasestorage.app',
    iosBundleId: 'com.example.medicaments',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmESOcxINXv7TB-8baBaKgf2k_dxNEtFI',
    appId: '1:459784963936:web:36d74217b030005ad30005',
    messagingSenderId: '459784963936',
    projectId: 'medicaments-f5daa',
    authDomain: 'medicaments-f5daa.firebaseapp.com',
    databaseURL: 'https://medicaments-f5daa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medicaments-f5daa.firebasestorage.app',
    measurementId: 'G-GDRCMLPXX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABFBY4des8YDbuU1QeppaDFI9YGAQhoe4',
    appId: '1:459784963936:android:5699ced54f7115c4d30005',
    messagingSenderId: '459784963936',
    projectId: 'medicaments-f5daa',
    databaseURL: 'https://medicaments-f5daa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medicaments-f5daa.firebasestorage.app',
  );

}